import {Position} from "./Position"
import { A1, A2, A3, A4, A5, A6, A7, A8, B1, C1, D1, E1, F1, G1, H1 } from "../constants/positions"

test("Position .up", () => {
    const a1 = new Position(A1)
    expect(a1.up()).toEqual(A2)
    expect(a1.up()).toEqual(A3)
    expect(a1.up()).toEqual(A4)
    expect(a1.up()).toEqual(A5)
    expect(a1.up()).toEqual(A6)
    expect(a1.up()).toEqual(A7)
    expect(a1.up()).toEqual(A8)
    expect(a1.up()).toEqual(A8)
})
test("Position .down", () => {
    const a8 = new Position(A8)
    expect(a8.down()).toEqual(A7)
    expect(a8.down()).toEqual(A6)
    expect(a8.down()).toEqual(A5)
    expect(a8.down()).toEqual(A4)
    expect(a8.down()).toEqual(A3)
    expect(a8.down()).toEqual(A2)
    expect(a8.down()).toEqual(A1)
    expect(a8.down()).toEqual(A1)
})
test("Position .right", () => {
    const a1 = new Position(A1)
    expect(a1.right()).toEqual(B1)
    expect(a1.right()).toEqual(C1)
    expect(a1.right()).toEqual(D1)
    expect(a1.right()).toEqual(E1)
    expect(a1.right()).toEqual(F1)
    expect(a1.right()).toEqual(G1)
    expect(a1.right()).toEqual(H1)
    expect(a1.right()).toEqual(H1)
})
test("Position .left", () => {
    const h1 = new Position(H1)
    expect(h1.left()).toEqual(G1)
    expect(h1.left()).toEqual(F1)
    expect(h1.left()).toEqual(E1)
    expect(h1.left()).toEqual(D1)
    expect(h1.left()).toEqual(C1)
    expect(h1.left()).toEqual(B1)
    expect(h1.left()).toEqual(A1)
    expect(h1.left()).toEqual(A1)
})